// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vuptvwbefbkjuadyojwf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ1cHR2d2JlZmJranVhZHlvandmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NTg0NTcsImV4cCI6MjA2NTIzNDQ1N30.9mNsfyVA9BFEmYhtdT4HgQPWIr8qhnfDn97VGDEfG9w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});